apiVersion: apps/v1
kind: Deployment
metadata:
  name: stava-depl
  namespace: zetterstrom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stava
  template:
    metadata:
      labels:
        app: stava
    spec:
      containers:
        - name: stava
          image: viktorzetterstrom/stava-zetterstrom-dev
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: stava-srv
  namespace: zetterstrom
spec:
  type: ClusterIP
  selector:
    app: stava
  ports:
    - name: stava
      protocol: TCP
      port: 80
      targetPort: 5000
